title: "Greg Schofield"
email: greg.c.schofield@gmail.com
description: >-
  Customer Architect, DevOps Specialist and Ruby Enthusiast
url: "https://gscho.github.io"
github_username:  gscho
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
show_downloads: false
github:
  is_user_page: true
  is_project_page: false
